const BLOG = {
  title: "mesh.",
  author: "mesh.",
  email: "web@growmesh.io",
  link: "https://growmesh.io",
  description: "Community for hackers and builders - mesh blog",
  lang: "en-US",
  timezone: "Europe/Budapest",
  appearance: "dark",
  font: "sans-serif",
  lightBackground: "#ffffff",
  darkBackground: "#18181B",
  path: "/blog",
  since: 2023,
  postsPerPage: 7,
  sortByDate: true,
  showAbout: true,
  showArchive: true,
  autoCollapsedNavBar: false,
  ogImageGenerateURL: "https://og-image-craigary.vercel.app",
  socialLink: "https://x.com/growmesh_io",
  seo: {
    keywords: [
      "mesh.",
      "growmesh",
      "mesh",
      "hacker",
      "builder",
      "talent",
      "launchpad",
      "cohort",
      "community",
      "builder space",
      "budapest",
      "startup",
      "tech",
      "innovation",
      "entrepreneur",
      "developer",
      "designer",
      "blog",
    ],
    googleSiteVerification: "",
  },
  notionPageId: process.env.NOTION_PAGE_ID,
  notionAccessToken: process.env.NOTION_ACCESS_TOKEN,
  analytics: {
    provider: "",
    ackeeConfig: {
      tracker: "",
      dataAckeeServer: "",
      domainId: "",
    },
    gaConfig: {
      measurementId: "",
    },
  },
  comment: {
    provider: "",
    gitalkConfig: {
      repo: "",
      owner: "",
      admin: [],
      clientID: "",
      clientSecret: "",
      distractionFreeMode: false,
    },
    utterancesConfig: {
      repo: "",
    },
    cusdisConfig: {
      appId: "",
      host: "https://cusdis.com",
      scriptSrc: "https://cusdis.com/js/cusdis.es.js",
    },
  },
  isProd: process.env.VERCEL_ENV === "production",
};

export default BLOG;
